import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "./components/Navbar";
// import Image from "next/image";
// import Link from "next/link";
// import Logo from "./logo.png";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icons: {
    icon: '/icons/logo.png'
  },
  title: "Next Mobile Ventures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin: "0px"}}>
        <Navbar />
        <hr style={{margin: "0px", border: "0px", background: "black", height : "5px", position: "sticky", top : "75px", zIndex: "2"}}></hr>
        {children}
      </body>
    </html>
  );
}
